name: Update Helm Chart Version

on:
  pull_request:
    branches:
      - main

env:
  # terraform-planner-service user in master account owns these keys
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  changed-files-job:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      matrix: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: tj-actions/changed-files@v40
        id: changed-files
        with:
          dir_names: true
          dir_names_max_depth: 2
          files: charts/**
          json: true
          quotepath: false
          escape_json: false

      - name: List all changed files
        run: echo '${{ steps.changed-files.outputs.all_changed_files }}'

  matrix-job:
    needs: changed-files-job
    runs-on: ubuntu-latest
    strategy:
      matrix:
        files: ${{ fromJSON(needs.changed-files-job.outputs.matrix) }}
    permissions:
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Matrix Job
        run: |
          echo "Running matrix job for changed file: ${{ matrix.files }}"

      # - uses: aws-actions/configure-aws-credentials@v3
      #   with:
      #     aws-region: us-east-2
      #     role-to-assume: arn:aws:iam::927377145031:role/Terraform-ReadOnly
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     role-skip-session-tagging: true # don't tag session - LZA doesn't deploy the trust relationship configs for this

      - name: Update Helm Chart Version
        run: |
          for file in ${{ matrix.files }}; do
            echo $file
            if [[ $file == "Chart.yaml" ]]; then
              yq e '.version = "0.0.4"' -i $file
            fi
          done

      - name: Set up Helm
        uses: azure/setup-helm@v3.5

      - name: Install helm s3 plugin
        run: helm plugin install https://github.com/hypnoglow/helm-s3.git

      - name: run update version script
        id: updated-version-script
        run: sh ./scripts/update-version.sh

      - name: fetch environment and service from pull request title
        id: fetch-silo-env-svc-names
        run: sh ./scripts/update-version.sh

      - name: update helm chart verison
        working-directory: ${{ matrix.changed_files }}
        run: yq e ".version = \"${{ steps.updated-version-script.outputs.new_version }}\"" -i Chart.yaml

      - uses: mshick/add-pr-comment@v2
        with:
          message: |
            Helm chart for service ${{ steps.fetch-silo-env-svc-names.outputs.service }} will be update to version ${{ steps.updated-version-script.outputs.new_version }}
