name: Pull Request Approved

on:
  pull_request_review:
    types: [submitted]
jobs:
  changed-files-job:
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved'
    permissions:
      pull-requests: read
    outputs:
      matrix: ${{ steps.changed-files.outputs.all_changed_files }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: changed files
        uses: tj-actions/changed-files@v40
        id: changed-files
        with:
          escape_json: false
          dir_names: true
          dir_names_max_depth: 2
          files: charts/**
          json: true
          quotepath: false

      - name: List all changed files
        run: echo '${{ steps.changed-files.outputs.all_changed_files }}'

  build:
    needs: [changed-files-job]
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - uses: tj-actions/changed-files@v40
        id: changed-file-chart-yaml
        with:
          escape_json: false
          files: ${{ matrix.files }}/Chart.yaml
          json: true
          quotepath: false

      - name: update file permission
        run: chmod +x ./.github/scripts/*

      - name: set service value
        run: |
          value=$(echo "${{ matrix.files }}" | cut -d"/" -f2)
          echo "Value: $value"
          echo "service=$value" >> "$GITHUB_ENV"

      - name: Set up Helm
        uses: azure/setup-helm@v3.5

      - uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-skip-session-tagging: true

      - name: Install helm s3 plugin
        run: |
          helm plugin install https://github.com/hypnoglow/helm-s3.git
          helm repo add service-helm-charts s3://service-helm-charts

      - name: check for changes in chart.yaml
        run: |
          echo '${{ steps.changed-file-chart-yaml.outputs.all_changed_files }}' 
          ./.github/scripts/pr-approved.sh '${{ steps.changed-file-chart-yaml.outputs.all_changed_files_count }}' '${{ matrix.files }}'
